// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: internal/northbound/pb/xunji.proto

package northboundpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	XunjiIngress_PushRealtime_FullMethodName = "/northboundpb.XunjiIngress/PushRealtime"
	XunjiIngress_PushAlarm_FullMethodName    = "/northboundpb.XunjiIngress/PushAlarm"
)

// XunjiIngressClient is the client API for XunjiIngress service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XunjiIngressClient interface {
	PushRealtime(ctx context.Context, in *PushRealtimeRequest, opts ...grpc.CallOption) (*PushAck, error)
	PushAlarm(ctx context.Context, in *PushAlarmRequest, opts ...grpc.CallOption) (*PushAck, error)
}

type xunjiIngressClient struct {
	cc grpc.ClientConnInterface
}

func NewXunjiIngressClient(cc grpc.ClientConnInterface) XunjiIngressClient {
	return &xunjiIngressClient{cc}
}

func (c *xunjiIngressClient) PushRealtime(ctx context.Context, in *PushRealtimeRequest, opts ...grpc.CallOption) (*PushAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushAck)
	err := c.cc.Invoke(ctx, XunjiIngress_PushRealtime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xunjiIngressClient) PushAlarm(ctx context.Context, in *PushAlarmRequest, opts ...grpc.CallOption) (*PushAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushAck)
	err := c.cc.Invoke(ctx, XunjiIngress_PushAlarm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XunjiIngressServer is the server API for XunjiIngress service.
// All implementations must embed UnimplementedXunjiIngressServer
// for forward compatibility.
type XunjiIngressServer interface {
	PushRealtime(context.Context, *PushRealtimeRequest) (*PushAck, error)
	PushAlarm(context.Context, *PushAlarmRequest) (*PushAck, error)
	mustEmbedUnimplementedXunjiIngressServer()
}

// UnimplementedXunjiIngressServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedXunjiIngressServer struct{}

func (UnimplementedXunjiIngressServer) PushRealtime(context.Context, *PushRealtimeRequest) (*PushAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushRealtime not implemented")
}
func (UnimplementedXunjiIngressServer) PushAlarm(context.Context, *PushAlarmRequest) (*PushAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushAlarm not implemented")
}
func (UnimplementedXunjiIngressServer) mustEmbedUnimplementedXunjiIngressServer() {}
func (UnimplementedXunjiIngressServer) testEmbeddedByValue()                      {}

// UnsafeXunjiIngressServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XunjiIngressServer will
// result in compilation errors.
type UnsafeXunjiIngressServer interface {
	mustEmbedUnimplementedXunjiIngressServer()
}

func RegisterXunjiIngressServer(s grpc.ServiceRegistrar, srv XunjiIngressServer) {
	// If the following call pancis, it indicates UnimplementedXunjiIngressServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&XunjiIngress_ServiceDesc, srv)
}

func _XunjiIngress_PushRealtime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRealtimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XunjiIngressServer).PushRealtime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XunjiIngress_PushRealtime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XunjiIngressServer).PushRealtime(ctx, req.(*PushRealtimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XunjiIngress_PushAlarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushAlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XunjiIngressServer).PushAlarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XunjiIngress_PushAlarm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XunjiIngressServer).PushAlarm(ctx, req.(*PushAlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// XunjiIngress_ServiceDesc is the grpc.ServiceDesc for XunjiIngress service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XunjiIngress_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "northboundpb.XunjiIngress",
	HandlerType: (*XunjiIngressServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushRealtime",
			Handler:    _XunjiIngress_PushRealtime_Handler,
		},
		{
			MethodName: "PushAlarm",
			Handler:    _XunjiIngress_PushAlarm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/northbound/pb/xunji.proto",
}
