// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.4
// source: internal/northbound/pb/xunji.proto

package northboundpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushRealtimeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceId        int64                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceName      string                 `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	ProductKey      string                 `protobuf:"bytes,3,opt,name=product_key,json=productKey,proto3" json:"product_key,omitempty"`
	DeviceKey       string                 `protobuf:"bytes,4,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,5,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	Fields          map[string]string      `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PushRealtimeRequest) Reset() {
	*x = PushRealtimeRequest{}
	mi := &file_internal_northbound_pb_xunji_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRealtimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRealtimeRequest) ProtoMessage() {}

func (x *PushRealtimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_northbound_pb_xunji_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRealtimeRequest.ProtoReflect.Descriptor instead.
func (*PushRealtimeRequest) Descriptor() ([]byte, []int) {
	return file_internal_northbound_pb_xunji_proto_rawDescGZIP(), []int{0}
}

func (x *PushRealtimeRequest) GetDeviceId() int64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *PushRealtimeRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *PushRealtimeRequest) GetProductKey() string {
	if x != nil {
		return x.ProductKey
	}
	return ""
}

func (x *PushRealtimeRequest) GetDeviceKey() string {
	if x != nil {
		return x.DeviceKey
	}
	return ""
}

func (x *PushRealtimeRequest) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *PushRealtimeRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type PushAlarmRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceId        int64                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceName      string                 `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	ProductKey      string                 `protobuf:"bytes,3,opt,name=product_key,json=productKey,proto3" json:"product_key,omitempty"`
	DeviceKey       string                 `protobuf:"bytes,4,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`
	FieldName       string                 `protobuf:"bytes,5,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	ActualValue     float64                `protobuf:"fixed64,6,opt,name=actual_value,json=actualValue,proto3" json:"actual_value,omitempty"`
	Threshold       float64                `protobuf:"fixed64,7,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Operator        string                 `protobuf:"bytes,8,opt,name=operator,proto3" json:"operator,omitempty"`
	Severity        string                 `protobuf:"bytes,9,opt,name=severity,proto3" json:"severity,omitempty"`
	Message         string                 `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	TriggeredUnixMs int64                  `protobuf:"varint,11,opt,name=triggered_unix_ms,json=triggeredUnixMs,proto3" json:"triggered_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PushAlarmRequest) Reset() {
	*x = PushAlarmRequest{}
	mi := &file_internal_northbound_pb_xunji_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushAlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushAlarmRequest) ProtoMessage() {}

func (x *PushAlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_northbound_pb_xunji_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushAlarmRequest.ProtoReflect.Descriptor instead.
func (*PushAlarmRequest) Descriptor() ([]byte, []int) {
	return file_internal_northbound_pb_xunji_proto_rawDescGZIP(), []int{1}
}

func (x *PushAlarmRequest) GetDeviceId() int64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *PushAlarmRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *PushAlarmRequest) GetProductKey() string {
	if x != nil {
		return x.ProductKey
	}
	return ""
}

func (x *PushAlarmRequest) GetDeviceKey() string {
	if x != nil {
		return x.DeviceKey
	}
	return ""
}

func (x *PushAlarmRequest) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *PushAlarmRequest) GetActualValue() float64 {
	if x != nil {
		return x.ActualValue
	}
	return 0
}

func (x *PushAlarmRequest) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *PushAlarmRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *PushAlarmRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *PushAlarmRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PushAlarmRequest) GetTriggeredUnixMs() int64 {
	if x != nil {
		return x.TriggeredUnixMs
	}
	return 0
}

type PushAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushAck) Reset() {
	*x = PushAck{}
	mi := &file_internal_northbound_pb_xunji_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushAck) ProtoMessage() {}

func (x *PushAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_northbound_pb_xunji_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushAck.ProtoReflect.Descriptor instead.
func (*PushAck) Descriptor() ([]byte, []int) {
	return file_internal_northbound_pb_xunji_proto_rawDescGZIP(), []int{2}
}

func (x *PushAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_northbound_pb_xunji_proto protoreflect.FileDescriptor

const file_internal_northbound_pb_xunji_proto_rawDesc = "" +
	"\n" +
	"\"internal/northbound/pb/xunji.proto\x12\fnorthboundpb\"\xc1\x02\n" +
	"\x13PushRealtimeRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x03R\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\x12\x1f\n" +
	"\vproduct_key\x18\x03 \x01(\tR\n" +
	"productKey\x12\x1d\n" +
	"\n" +
	"device_key\x18\x04 \x01(\tR\tdeviceKey\x12*\n" +
	"\x11timestamp_unix_ms\x18\x05 \x01(\x03R\x0ftimestampUnixMs\x12E\n" +
	"\x06fields\x18\x06 \x03(\v2-.northboundpb.PushRealtimeRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xee\x02\n" +
	"\x10PushAlarmRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x03R\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\x12\x1f\n" +
	"\vproduct_key\x18\x03 \x01(\tR\n" +
	"productKey\x12\x1d\n" +
	"\n" +
	"device_key\x18\x04 \x01(\tR\tdeviceKey\x12\x1d\n" +
	"\n" +
	"field_name\x18\x05 \x01(\tR\tfieldName\x12!\n" +
	"\factual_value\x18\x06 \x01(\x01R\vactualValue\x12\x1c\n" +
	"\tthreshold\x18\a \x01(\x01R\tthreshold\x12\x1a\n" +
	"\boperator\x18\b \x01(\tR\boperator\x12\x1a\n" +
	"\bseverity\x18\t \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\n" +
	" \x01(\tR\amessage\x12*\n" +
	"\x11triggered_unix_ms\x18\v \x01(\x03R\x0ftriggeredUnixMs\"=\n" +
	"\aPushAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9c\x01\n" +
	"\fXunjiIngress\x12H\n" +
	"\fPushRealtime\x12!.northboundpb.PushRealtimeRequest\x1a\x15.northboundpb.PushAck\x12B\n" +
	"\tPushAlarm\x12\x1e.northboundpb.PushAlarmRequest\x1a\x15.northboundpb.PushAckBDZBgithub.com/gonglijing/xunjiFsu/internal/northbound/pb;northboundpbb\x06proto3"

var (
	file_internal_northbound_pb_xunji_proto_rawDescOnce sync.Once
	file_internal_northbound_pb_xunji_proto_rawDescData []byte
)

func file_internal_northbound_pb_xunji_proto_rawDescGZIP() []byte {
	file_internal_northbound_pb_xunji_proto_rawDescOnce.Do(func() {
		file_internal_northbound_pb_xunji_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_northbound_pb_xunji_proto_rawDesc), len(file_internal_northbound_pb_xunji_proto_rawDesc)))
	})
	return file_internal_northbound_pb_xunji_proto_rawDescData
}

var file_internal_northbound_pb_xunji_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_northbound_pb_xunji_proto_goTypes = []any{
	(*PushRealtimeRequest)(nil), // 0: northboundpb.PushRealtimeRequest
	(*PushAlarmRequest)(nil),    // 1: northboundpb.PushAlarmRequest
	(*PushAck)(nil),             // 2: northboundpb.PushAck
	nil,                         // 3: northboundpb.PushRealtimeRequest.FieldsEntry
}
var file_internal_northbound_pb_xunji_proto_depIdxs = []int32{
	3, // 0: northboundpb.PushRealtimeRequest.fields:type_name -> northboundpb.PushRealtimeRequest.FieldsEntry
	0, // 1: northboundpb.XunjiIngress.PushRealtime:input_type -> northboundpb.PushRealtimeRequest
	1, // 2: northboundpb.XunjiIngress.PushAlarm:input_type -> northboundpb.PushAlarmRequest
	2, // 3: northboundpb.XunjiIngress.PushRealtime:output_type -> northboundpb.PushAck
	2, // 4: northboundpb.XunjiIngress.PushAlarm:output_type -> northboundpb.PushAck
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_northbound_pb_xunji_proto_init() }
func file_internal_northbound_pb_xunji_proto_init() {
	if File_internal_northbound_pb_xunji_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_northbound_pb_xunji_proto_rawDesc), len(file_internal_northbound_pb_xunji_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_northbound_pb_xunji_proto_goTypes,
		DependencyIndexes: file_internal_northbound_pb_xunji_proto_depIdxs,
		MessageInfos:      file_internal_northbound_pb_xunji_proto_msgTypes,
	}.Build()
	File_internal_northbound_pb_xunji_proto = out.File
	file_internal_northbound_pb_xunji_proto_goTypes = nil
	file_internal_northbound_pb_xunji_proto_depIdxs = nil
}
